import type { Metadata } from 'next';
import './globals.css';
import { Edu_VIC_WA_NT_Beginner } from 'next/font/google';
import { ThemeContainer, Header } from '@/components';

const enFont = Edu_VIC_WA_NT_Beginner({
     subsets: ['latin'],
     variable: '--font-edu',
     display: 'swap',
});
export const metadata: Metadata = {
     title: 'Create Next App',
     description: 'Generated by create next app',
};


     export default function RootLayout({
          children,
     }: {
          children: React.ReactNode;
     }) {
          return (
             <html lang="en" id="html">
          <body className={` ${enFont.className}  antialiased`}>
               <ThemeContainer>
                    <Header />
                    {children}
               </ThemeContainer>
          </body>
     </html>)
     
     }